USE [SkatingLogDB]
GO

CREATE TABLE Users(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(50) NOT NULL,
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
    Email NVARCHAR(255) NOT NULL,
    PasswordHash VARBINARY(MAX) NOT NULL,
    PasswordSalt VARBINARY(MAX) NOT NULL
)

ALTER TABLE Users
ADD CONSTRAINT UQ_Username UNIQUE (Username),
    CONSTRAINT UQ_Email UNIQUE (Email)