USE [TimeEntryDB]
GO

/****** Object:  Table [dbo].[Maintenance]    Script Date: 8/10/2022 10:25:52 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Level](
	[LevelId] [INT] IDENTITY(1,1) NOT NULL,
	[UpdatedDateTimeStamp] [DATETIME2](7) NOT NULL,
	[EffectiveDateTime] [DATETIME2](7) NOT NULL,
	[LevelA] [INT] NOT NULL,
	[LevelB] [INT] NOT NULL,
	[LevelC] [INT] NOT NULL,
	[LevelD] [INT] NOT NULL,
	[LevelE] [INT] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[LevelId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

